In [66]:
import nltk
import random
from nltk.corpus import movie_reviews

In [67]:
len(set(movie_reviews.words()))

39768

In [68]:
documents = []
sentiment_category = []

for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        documents.append(movie_reviews.words(fileid))
        sentiment_category.append(category)

In [69]:
documents[0]

['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...]

In [83]:
from nltk.corpus import stopwords
english_stopwords=stopwords.words('english')
english_stopwords=[word for word in english_stopwords if word != 'not']

In [84]:
specal_chars=[",","@","?","."," ","/","\\","(",")","<",">","-","_",'"','!','*','=']

cleaned_documents=[]
for doc in documents:
    w_list=[]
    for word in doc:
        if(word not in english_stopwords and word not in specal_chars and len(word)>2):
            w_list.append(word.lower())
    cleaned_documents.append(w_list)

In [85]:
print(cleaned_documents[0])

['plot', 'two', 'teen', 'couples', 'church', 'party', 'drink', 'drive', 'get', 'accident', 'one', 'guys', 'dies', 'girlfriend', 'continues', 'see', 'life', 'nightmares', 'deal', 'watch', 'movie', 'sorta', 'find', 'critique', 'mind', 'fuck', 'movie', 'teen', 'generation', 'touches', 'cool', 'idea', 'presents', 'bad', 'package', 'makes', 'review', 'even', 'harder', 'one', 'write', 'since', 'generally', 'applaud', 'films', 'attempt', 'break', 'mold', 'mess', 'head', 'lost', 'highway', 'memento', 'good', 'bad', 'ways', 'making', 'types', 'films', 'folks', 'snag', 'one', 'correctly', 'seem', 'taken', 'pretty', 'neat', 'concept', 'executed', 'terribly', 'problems', 'movie', 'well', 'main', 'problem', 'simply', 'jumbled', 'starts', 'normal', 'downshifts', 'fantasy', 'world', 'audience', 'member', 'idea', 'going', 'dreams', 'characters', 'coming', 'back', 'dead', 'others', 'look', 'like', 'dead', 'strange', 'apparitions', 'disappearances', 'looooot', 'chase', 'scenes', 'tons', 'weird', 'things

In [86]:
review_text_list=[]
for d in cleaned_documents:
    review_text_list.append(" ".join(d))

In [87]:
review_text_list[0]

'plot two teen couples church party drink drive get accident one guys dies girlfriend continues see life nightmares deal watch movie sorta find critique mind fuck movie teen generation touches cool idea presents bad package makes review even harder one write since generally applaud films attempt break mold mess head lost highway memento good bad ways making types films folks snag one correctly seem taken pretty neat concept executed terribly problems movie well main problem simply jumbled starts normal downshifts fantasy world audience member idea going dreams characters coming back dead others look like dead strange apparitions disappearances looooot chase scenes tons weird things happen simply not explained personally mind trying unravel film every give clue get kind fed film biggest problem obviously got big secret hide seems want hide completely final five minutes make things entertaining thrilling even engaging meantime not really sad part arrow dig flicks like actually figured ha

In [88]:
print(review_text_list[:2])
print(sentiment_category[:2])

['plot two teen couples church party drink drive get accident one guys dies girlfriend continues see life nightmares deal watch movie sorta find critique mind fuck movie teen generation touches cool idea presents bad package makes review even harder one write since generally applaud films attempt break mold mess head lost highway memento good bad ways making types films folks snag one correctly seem taken pretty neat concept executed terribly problems movie well main problem simply jumbled starts normal downshifts fantasy world audience member idea going dreams characters coming back dead others look like dead strange apparitions disappearances looooot chase scenes tons weird things happen simply not explained personally mind trying unravel film every give clue get kind fed film biggest problem obviously got big secret hide seems want hide completely final five minutes make things entertaining thrilling even engaging meantime not really sad part arrow dig flicks like actually figured h

In [89]:
all_words = []
for w in movie_reviews.words():
    word= w.lower()
    if(word not in english_stopwords and word not in specal_chars and len(word)>2):
        all_words.append(w.lower())

In [91]:
vaocab_length=len(set(all_words))

In [92]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense

In [ ]:
one_hot_review=[one_hot(doc,vaocab_length) for doc in review_text_list]

In [98]:
print(one_hot_review[:2])

[[23619, 2087, 4147, 8210, 33744, 14110, 23981, 29476, 10881, 7975, 38937, 14784, 14042, 28158, 7586, 20174, 2931, 13434, 38777, 11138, 4817, 18478, 9181, 20584, 31752, 22323, 4817, 4147, 21767, 35076, 29866, 37125, 37089, 1224, 26136, 8203, 5870, 15459, 12644, 38937, 30152, 24460, 36850, 4053, 28018, 21248, 4901, 9715, 31447, 7249, 19728, 7927, 33260, 35260, 1224, 9015, 35701, 12026, 28018, 20792, 5754, 38937, 33066, 27646, 33387, 31065, 12677, 27673, 21003, 4026, 18847, 4817, 31287, 14778, 11769, 10168, 34474, 9868, 18480, 28455, 23246, 5659, 19804, 27090, 37125, 15809, 13314, 18673, 26603, 17272, 2433, 33702, 25346, 1594, 2433, 30710, 11605, 8611, 17066, 12814, 31470, 13569, 9348, 32669, 17693, 10168, 33226, 4819, 2122, 31752, 36067, 26377, 34041, 15965, 15703, 33579, 10881, 27768, 25383, 34041, 21285, 11769, 1164, 19220, 12578, 4143, 5694, 30091, 4765, 5694, 24812, 20169, 31424, 36763, 62, 32669, 5092, 38099, 15459, 14962, 938, 33226, 2301, 30786, 30476, 21757, 796, 5879, 1594, 140

In [100]:
padding_length=300

pad_seq=pad_sequences(one_hot_review,truncating='post',padding='post',maxlen=padding_length)
print(pad_seq)

[[23619  2087  4147 ... 20299  2087 36541]
 [29926 21297 20319 ...     0     0     0]
 [ 1290  1594    62 ...     0     0     0]
 ...
 [19211  8926 16319 ... 33440 29207  4528]
 [19731 20636 28907 ... 32791 11632 15459]
 [28619 20868 33872 ...   451 34041  6645]]


In [109]:
Y=map(lambda x: 0 if x== 'neg' else 1, sentiment_category)
Y=list(Y)
Y[:3]

[0, 0, 0]

In [111]:
from keras.callbacks import TensorBoard,EarlyStopping

In [143]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(pad_seq, np.array(Y),test_size=0.20)

In [144]:
print(X_train.shape)
print(X_test.shape)

(1600, 300)
(400, 300)


In [152]:
model=Sequential()
model.add(Embedding(vaocab_length,embedding_length,input_length=padding_length))  #padding_length=15
model.add(LSTM(200,return_sequences=True))
model.add(Dense(100, activation='relu'))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_11 (Embedding)     (None, 300, 5)            196165    
_________________________________________________________________
lstm_11 (LSTM)               (None, 300, 200)          164800    
_________________________________________________________________
dense_8 (Dense)              (None, 300, 100)          20100     
_________________________________________________________________
lstm_12 (LSTM)               (None, 100)               80400     
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 101       
Total params: 461,566
Trainable params: 461,566
Non-trainable params: 0
_________________________________________________________________
None


In [153]:
early_stopping_cb = EarlyStopping(patience=10,restore_best_weights=True)
model.fit(X_train,y_train,epochs=1000000,validation_data=(X_test, y_test), verbose=1,callbacks=[early_stopping_cb])

Epoch 1/1000000
50/50 [==============================] - 23s 457ms/step - loss: 0.6938 - accuracy: 0.5063 - val_loss: 0.6935 - val_accuracy: 0.4700
Epoch 2/1000000
50/50 [==============================] - 23s 454ms/step - loss: 0.6929 - accuracy: 0.5175 - val_loss: 0.6889 - val_accuracy: 0.5625
Epoch 3/1000000
50/50 [==============================] - 23s 452ms/step - loss: 0.6594 - accuracy: 0.6363 - val_loss: 0.6852 - val_accuracy: 0.5900
Epoch 4/1000000
50/50 [==============================] - 23s 464ms/step - loss: 0.4266 - accuracy: 0.7837 - val_loss: 0.8446 - val_accuracy: 0.6025
Epoch 5/1000000
50/50 [==============================] - 23s 454ms/step - loss: 0.3285 - accuracy: 0.8281 - val_loss: 0.9878 - val_accuracy: 0.5250
Epoch 6/1000000
50/50 [==============================] - 23s 452ms/step - loss: 0.3030 - accuracy: 0.8281 - val_loss: 1.0203 - val_accuracy: 0.5525
Epoch 7/1000000
50/50 [==============================] - 23s 454ms/step - loss: 0.2437 - accuracy: 0.8544 - val_